### ISSUE TITLE
Breaks formatting dropdowns in any text editor

### ISSUE THREAD

**Issue by Gawdl3y** [LebombJames/button-feel#1]
When this module is installed/active, the formatting dropdowns (for paragraph style/headings/inline/etc and for fonts) no longer work (on v10).  
I have no advice as to why. There's no reason I can discern for a CSS `filter` to cause breakage like this. 😭

**Comment by LebombJames** [comment]
How exactly is it broken? The only strange thing to me is that the entire list darkens, and that's only on the ProseMirror sheet

**Comment by Gawdl3y** [comment]
This is what happens when we try to select any of the options in the dropdown - they just literally don't do anything. Disabling the module resolved it. FWIW, we're both using Chrome 105.

https://user-images.githubusercontent.com/279900/189782786-7da0ead9-f4d4-40f3-a025-8a397911033e.mp4

**Comment by LebombJames** [comment]
Interesting, I can reproduce it on the 5e sheet, but not in a standard JE. Either way, the fix for the entire list darkening also fixes this. Will push a fix out. This is what I get for being a PF2e player 😅
