### ISSUE TITLE
[Bug] Dorako UI Conflict

### ISSUE THREAD

**Issue by Crowguard** [LebombJames/button-feel#2]
Having Button Feel active with Dorako UI causes the Chat Tab to render improperly depending on which Foundry version you're using.

https://github.com/Dorako/pf2e-dorako-ui/issues/206

### Foundry 10.303

Chat Tab button overlaps the chat messages.

![image](https://github.com/LebombJames/button-feel/assets/99844555/891840c6-ccd1-4b11-9610-4cde5cd4ca09)

Dorako 2.2.4
Button Feel 1.1.2
PF2 4.12.9

### Foundry 11.304

Chat messages are instead overlapping the tab buttons.

![image](https://github.com/LebombJames/button-feel/assets/99844555/972b06dc-a3c4-45d3-b633-61811edbfded)

Dorako 2.2.4
Button Feel 1.1.2
PF2 5.1.0

**Comment by Spappz** [comment]
Resolved on Dorako's end in [v2.6.4](https://github.com/Dorako/pf2e-dorako-ui/releases/tag/v2.6.4)
